### ISSUE TITLE
2016 general counties missing early vote/election day breakdowns

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-tx#10]
- [ ] Angelina
- [ ] Atascosa
- [ ] Austin
- [ ] Bailey
- [ ] Bandera
- [ ] Bee
- [x] Bell
- [ ] Bexar
- [ ] Blanco
- [ ] Brazoria
- [ ] Brazos
- [ ] Briscoe
- [ ] Brown
- [ ] Burleson
- [ ] Caldwell
- [ ] Calhoun
- [ ] Cochran
- [ ] Colorado
- [ ] Cooke
- [ ] Crane
- [ ] Crosby
- [ ] Dallam
- [ ] Dallas
- [ ] Delta
- [ ] DeWitt
- [ ] Dickens
- [ ] Eastland
- [ ] Ector
- [ ] Edwards
- [ ] El Paso
- [ ] Erath
- [ ] Fort Bend
- [ ] Freestone
- [ ] Frio
- [ ] Gaines
- [ ] Galveston
- [ ] Goliad
- [ ] Gonzales
- [ ] Gray
- [ ] Grayson
- [ ] Hansford
- [ ] Hays
- [ ] Houston
- [ ] Howard
- [ ] Jasper
- [ ] Jim Hogg
- [ ] Jim Wells
- [ ] Kaufman
- [ ] Kleberg
- [ ] Lavaca
- [ ] Leon
- [ ] Liberty
- [ ] Limestone
- [ ] Lubbock
- [ ] Marion
- [ ] Martin
- [ ] Midland
- [ ] Mills
- [ ] Mitchell
- [ ] Montague
- [ ] Montgomery
- [ ] Moore
- [ ] Morris
- [ ] Navarro
- [ ] Ochiltree
- [ ] Orange
- [ ] Palo Pinto
- [ ] Parmer
- [ ] Randall
- [ ] Real
- [ ] Robertson
- [ ] San Augustine
- [ ] San Jacinto
- [ ] San Patricio
- [ ] Schleicher
- [ ] Scurry
- [ ] Smith
- [ ] Somervell
- [ ] Starr
- [ ] Stephens
- [ ] Sutton
- [ ] Swisher
- [ ] Taylor
- [ ] Terry
- [ ] Titus
- [ ] Travis
- [ ] Upshur
- [ ] Walker
- [ ] Waller
- [ ] Wichita
- [ ] Wilbarger
- [ ] Yoakum

**Comment by lephead** [comment]
Good luck with Brazos.  I did everything I could to get it out of her.  Brazos used to do it another way, where they actually did a early and an election day canvass.  They got the system I call "the Texas style"  that appears not to have our info.
