### ISSUE TITLE
Travis County 2016 Republican Primary discrepancies

### ISSUE THREAD

**Issue by alanhuang122** [openelections/openelections-data-tx#23]
The Presidential totals in the [CSV file](https://raw.githubusercontent.com/openelections/openelections-sources-tx/master/2016/TRAVIS_COUNTY-2016_Republican_Party_Primary_Election_312016-03%20REP_SOSexport.csv) for that election have discrepancies with the official Travis County [results PDF](http://traviscountyclerk.org/eclerk/content/images/election_results/2016.03.01/Final/20160301repcume.pdf) and the Secretary of State's [site](http://elections.sos.state.tx.us/elchist273_county227.htm).
The sum of all votes for President in the CSV file is 84831, while the sum of all votes for President in the official cumulative results is 84844.
The CSV file is missing:

- 1 vote for Jeb Bush
- 1 vote for Ted Cruz
- 1 vote for John Kasich
- 1 vote for Rand Paul
- 9 votes for Marco Rubio.

I'll dig into it and see if I can't figure it out later this week.

**Comment by alanhuang122** [comment]
I've figured out where the missing votes were - they're in the "Precinct X - RZ" results.
...though I have no idea what a "RZ" precinct is.

**Comment by alanhuang122** [comment]
A possible clue: every vote cast in the "RZ" section is listed under "Early Voting".

**Comment by dwillis** [comment]
Interesting; might be worth asking the Travis County folks about.

**Comment by alanhuang122** [comment]
I've sent an email to elections@traviscountytx.gov, and will update this if/when I get a response.

**Comment by alanhuang122** [comment]
Travis County Elections has not responded to me, but I figured out the issue. The proverbial lightbulb went off in my brain once I realized that the only races listed on the precinct results were federal races (President, U.S. House). I recalled that there was a certain scenario wherein a Texas voter would only be allowed to cast ballots for federal races and not local ones.

The answer turned out to be voters who moved to Travis County from another county voting a "limited ballot", as outlined [here](http://traviscountyclerk.org/eclerk/Content.do?code=E.8).
Additionally, the page states that "Limited Ballots are available ONLY during the Early Voting period for the upcoming election and are ONLY processed at the Travis County Elections offices...", which explains why every vote was counted in Early Voting.

It turns out that these votes were counted for the U.S. House races, and for the Democratic presidential primary. The only race for which it was not counted in the precinct-level results was the Republican primary for President.

**Comment by dwillis** [comment]
@alanhuang122 That's some good sleuthing.

**Comment by alanhuang122** [comment]
I got a response from the county today. It turns out that my interpretation was incorrect - they're mail in ballots from overseas/military voters.

This makes sense, since limited ballots would cover statewide races as well as federal, and may not have necessarily had an associated precinct.

This does not affect the correctness of the data set in #40.
