### ISSUE TITLE
What encoding should csv files be in?

### ISSUE THREAD

**Issue by crass** [openelections/openelections-data-tx#258]
What encoding should the csv files be in?  I think the answer should be `utf8`.  However, `2018/20181106__tx__general__dewitt__precinct.csv` is encoded in the `latin` encoding.

**Comment by dwillis** [comment]
@crass yeah, states where we do county-by-county processing aren't all in the same format. Agree that it should be `utf8`. Will address.

**Comment by crass** [comment]
I wrote a simple python script for converting `latin` encoded files to `utf8` and the result is in #261.
