### ISSUE TITLE
2018 Dallas precinct file has odd ballot_style field

### ISSUE THREAD

**Issue by crass** [openelections/openelections-data-tx#265]
Dallas county precinct file, `2018/20180306__tx__primary__dallas__precinct.csv`, has `ballot_style` field which seems odd. What does it mean?  I'm looking at one of the [source files](https://raw.githubusercontent.com/openelections/openelections-sources-tx/master/2018/primary/Dallas%20County%20180306%20DEM%20Primary%20Election%20Final%20ASC%20Final%20for%20SOS.ASC) and I'm noticing that the `ballot_style` field is actually the precinct number.  And the precinct number corresponds to the first number in the "precinct name" field.

I'm not 100% sure that the `ballot_style` style field should be renamed as the `precinct` field.  But if not, it should probably be renamed or removed. If `ballot_style` should be renamed to `precinct`, the old `precinct` field should be removed.

**Comment by alanhuang122** [comment]
I was/am responsible for converting Dallas County's results files. Ballot style dictates what races a voter in a given precinct will have.
The issue of ballot style was addressed in #16.
In a nutshell, there was no harm seen in leaving it in. It can be safely ignored.
The `precinct` field is still the correct information, and is what would be used to map data: e.g., my precinct number is 2500 - the fact that I had ballot style 6303 for the 2018 primary election isn't important, and in fact, for the general election, I had ballot style 5610. In other words, `ballot_style` will change between elections for a given voter, but `precinct` generally will not.

**Comment by crass** [comment]
@alanhuang122, I don't mind leaving `ballot_style` in the results file.  But are you sure that `ballot_style` and `precinct` shouldn't be swapped?  According to [multiple](https://vip.sos.nd.gov/pdfs/checklists/ERM/ES&S_Election_Reporting_Manager_System_Operations_Procedures_7.5.7.0_Unity_3.2.1.0%5B1%5D.pdf#G10.35236) [sources](https://www.ri.gov/election/results/data_description.pdf), the third field in election ASC files is `precinct` which corresponds to the number value in `ballot_style`.  Why do you think its not?

**Comment by alanhuang122** [comment]
Precinct numbers in Dallas County only go up to 4664, see [here](https://www.dallascountyvotes.org/election-results-and-maps/voting-precincts-maps/2019-voting-precincts/); numbers greater than 5000, e.g., **cannot** be valid precinct numbers.

Yes, ES&S and the RI Secretary of State's office claim that characters 8-11 in the ASC file are the precinct number. In this case, however, *it is not*. If you look at Dallas County's precincts, you'll quickly realize this.

If you try to use `ballot_style` as the precinct number, you will not be able to correctly associate precincts with geographic locations.

**Comment by dwillis** [comment]
@crass @alanhuang122 going to mark this one as closed/wontfix.
