### ISSUE TITLE
2018 Sherman county rename odd early voting field names

### ISSUE THREAD

**Issue by crass** [openelections/openelections-data-tx#266]
In file `2018/20180306__tx__primary__sherman__precinct.csv` there are two fields `early_voting_ts` and `early_voting_os`.  What does the `os` and `ts` stand for?  My guess is that `os` are paper ballots and `ts` are machine ballots because other counties have early voting divided into machine and paper ballots and `os` has less ballots than `ts` as I'd expect of paper vs machine ballots. But I've been unable to confirm this. Regardless we should rename these fields to something intelligible.

**Comment by dwillis** [comment]
@crass I've dug into this and `os` and `ts` refer to two different models of voting machines used by some jurisdictions. We should document this somewhere but I am not going to change the column names.
