### ISSUE TITLE
2018 Shackelford lots of issues

### ISSUE THREAD

**Issue by crass** [openelections/openelections-data-tx#273]
The file `2018/20181106__tx__general__shackelford__precinct.csv` has several issues:

- Many rows do not have 10 columns, even though there are 10 headers. (eg. "Registered Voters" rows)
- There are many duplicate rows. (eg. "Registered Voters")

Would it be easier to recreate this with the source data?

**Comment by crass** [comment]
PR #274 fixes the first bullet in a trivial way, but does not address this issue fully.

**Comment by dwillis** [comment]
@crass Just to clarify, registered voters column will _never_ have `early_voting`, `election_day` or `absentee` values. I'll fix the duplicate rows issue, though.
