### ISSUE TITLE
Thousands separators in several files

### ISSUE THREAD

**Issue by taylorterry3** [openelections/openelections-data-tx#283]
Thanks for the quick fix on #282! I actually found many more instances of counts with thousands separators and quotes around them. I was considering just opening fire on them with regex, but there are also some combined precinct codes that end up looking similar so I'm hoping @dwillis can apply the same fix he used in Dallas. See below for examples, including some precincts false alarms.

```
openelections-data-tx $ egrep -rn "\"[0-9]{1,3},[0-9]{3}" | shuf -n 5
2014/20141104__tx__general__williamson__precinct.csv:883:Williamson,253,US Representative,District 31,REP,John Carter,"1,234",0,0
2014/20141104__tx__general__williamson__precinct.csv:6483:Williamson,204,County Judge,,REP,Dan A. Gattis,"1,050",0,0
2014/20141104__tx__general__williamson__precinct.csv:6861:Williamson,204,TX Prop 1,,NA,For (A Favor),"1,169",0,0
2016/counties/20160301__tx__primary__howard__precinct.csv:162:Howard,"207,207c",President,,REP,Uncommitted,4,1,3
2016/counties/20160301__tx__primary__howard__precinct.csv:11:Howard,"404,405",President,,REP,Rick Santorum,0,0,0
```

**Comment by dwillis** [comment]
@taylorterry3 Thanks! Fixing 2014 Williamson now; the Howard files are correct because the commas are in the precinct column.
