### ISSUE TITLE
Field coding error

### ISSUE THREAD

**Issue by adamConnerSax** [openelections/openelections-data-tx#284]
Thanks for all this work and the excellent data!
I've been working to use the precinct level files to aggregate statewide office results by state legislative district.  When parsing the files I've come across some badly escaped fields. In particulate in 
2018/counties/20181106__tx__general__harris__precinct.csv
There's a line
Harris,630,"Directors, Harris County Water Control HC WCID 89, Directors" Improvement District 89 (Vote for 2)",,,AK Babers,447,366,67,14

where the quotes end in the middle of the office field.  Thus messing up any standard csv parser.

**Comment by warwickmm** [comment]
I think this can be closed?

**Comment by adamConnerSax** [comment]
Yes!  Sorry! I fixed my version and didn't notice the fix here get merged.  Thanks!
