### ISSUE TITLE
Convert 2016 general precinct results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-tx#3]
Using [Tabula](http://tabula.technology/), OCR or whatever method you can, parse precinct-level results for the following counties. Original sources are in the [sources-tx repository](https://github.com/openelections/openelections-sources-tx/tree/master/2016).

The goal is to create a single CSV file for each county, with the following headers:

`county`, `precinct`, `office`, `district`, `party`, `candidate`, `votes`

The CSV files should be named `20161108__tx__general__{county}__precinct.csv`

- [x] Anderson
- [x] Andrews
- [x] Angelina
- [x] Aransas
- [x] Archer
- [x] Armstrong
- [x] Atascosa
- [x] Austin
- [x] Bailey
- [x] Bandera
- [x] Bastrop
- [x] Baylor
- [x] Bee
- [x] Bell
- [x] Bexar
- [x] Blanco
- [x] Borden
- [x] Bosque
- [x] Bowie
- [x] Brazoria
- [x] Brazos
- [x] Brewster
- [x] Briscoe
- [x] Brooks
- [x] Brown
- [x] Burleson
- [x] Burnet
- [x] Caldwell
- [x] Calhoun
- [x] Callahan
- [x] Cameron
- [x] Camp
- [x] Carson
- [x] Cass
- [x] Castro
- [x] Chambers
- [x] Cherokee
- [x] Childress
- [x] Clay
- [x] Cochran
- [x] Coke
- [x] Coleman
- [x] Collin
- [x] Collingsworth
- [x] Colorado
- [x] Comal
- [x] Comanche
- [x] Concho
- [x] Cooke
- [x] Coryell
- [x] Cottle
- [x] Crane
- [x] Crockett
- [x] Crosby
- [x] Culberson
- [x] Dallam
- [x] Dallas
- [x] Dawson
- [x] Deaf Smith
- [x] Delta
- [x] Denton
- [x] DeWitt
- [x] Dickens
- [x] Dimmit
- [x] Donley
- [x] Duval
- [x] Eastland
- [x] Ector
- [x] Edwards
- [x] Ellis
- [x] El Paso
- [x] Erath
- [x] Falls
- [x] Fannin
- [x] Fayette
- [x] Fisher
- [x] Floyd
- [x] Foard
- [x] Fort Bend
- [x] Franklin
- [x] Freestone
- [x] Frio
- [x] Gaines
- [x] Galveston
- [x] Garza
- [x] Gillespie
- [x] Glasscock
- [x] Goliad
- [x] Gonzales
- [x] Gray
- [x] Grayson
- [x] Gregg
- [x] Grimes
- [x] Guadalupe
- [x] Hale
- [x] Hall
- [x] Hamilton
- [x] Hansford
- [x] Hardeman
- [x] Hardin
- [x] Harris
- [x] Harrison
- [x] Hartley
- [x] Haskell
- [x] Hays
- [x] Hemphill
- [x] Henderson
- [x] Hidalgo
- [x] Hill
- [x] Hockley
- [x] Hood
- [x] Hopkins
- [x] Houston
- [x] Howard
- [x] Hudspeth
- [x] Hunt
- [x] Hutchinson
- [x] Irion
- [x] Jack
- [x] Jackson
- [x] Jasper
- [x] Jeff Davis
- [x] Jefferson
- [x] Jim Hogg
- [x] Jim Wells
- [x] Johnson
- [x] Jones
- [x] Karnes
- [x] Kaufman
- [x] Kendall
- [x] Kenedy
- [x] Kent
- [x] Kerr
- [x] Kimble
- [x] King
- [x] Kinney
- [x] Kleberg
- [x] Knox
- [x] Lamar
- [x] Lamb
- [x] Lampasas
- [x] La Salle
- [x] Lavaca
- [x] Lee
- [x] Leon
- [x] Liberty
- [x] Limestone
- [x] Lipscomb
- [x] Live Oak
- [x] Llano
- [x] Loving
- [x] Lubbock
- [x] Lynn
- [x] McCulloch
- [x] McLennan
- [x] McMullen
- [x] Madison
- [x] Marion
- [x] Martin
- [x] Mason
- [x] Matagorda
- [x] Maverick
- [x] Medina
- [x] Menard
- [x] Midland
- [x] Milam
- [x] Mills
- [x] Mitchell
- [x] Montague
- [x] Montgomery
- [x] Moore
- [x] Morris
- [x] Motley
- [x] Nacogdoches
- [x] Navarro
- [x] Newton
- [x] Nolan
- [x] Nueces
- [x] Ochiltree
- [x] Oldham
- [x] Orange
- [x] Palo Pinto
- [x] Panola
- [x] Parker
- [x] Parmer
- [x] Pecos
- [x] Polk
- [x] Potter
- [x] Presidio
- [x] Rains
- [x] Randall
- [x] Reagan
- [x] Real
- [x] Red River
- [x] Reeves (partial, missing parts of two precincts)
- [x] Refugio
- [x] Roberts
- [x] Robertson
- [x] Rockwall
- [x] Runnels
- [x] Rusk
- [x] Sabine
- [x] San Augustine
- [x] San Jacinto
- [x] San Patricio
- [x] San Saba
- [x] Schleicher
- [x] Scurry
- [x] Shackelford
- [x] Shelby
- [x] Sherman
- [x] Smith
- [x] Somervell
- [x] Starr
- [x] Stephens
- [x] Sterling
- [x] Stonewall
- [x] Sutton
- [x] Swisher
- [x] Tarrant
- [x] Taylor
- [x] Terrell
- [x] Terry
- [x] Throckmorton
- [x] Titus
- [x] Tom Green
- [x] Travis
- [x] Trinity
- [x] Tyler
- [x] Upshur
- [x] Upton
- [x] Uvalde
- [x] Val Verde
- [x] Van Zandt
- [x] Victoria
- [x] Walker
- [x] Waller
- [x] Ward
- [x] Washington
- [x] Webb
- [x] Wharton
- [x] Wheeler
- [x] Wichita
- [x] Wilbarger
- [x] Willacy
- [x] Williamson
- [x] Wilson
- [x] Winkler
- [x] Wise
- [x] Wood
- [x] Yoakum
- [x] Young
- [x] Zapata
- [x] Zavala

**Comment by jksinton** [comment]
I can help with Harris. I already converted some of it here: https://docs.google.com/spreadsheets/d/1Bd6f3OIM0f4E5N7CP6V5PI7C81xddE-MFU4UOB7n9yg/edit#gid=882286985

**Comment by dwillis** [comment]
@jksinton That's awesome, thanks! Can we just grab that and finish it off?

**Comment by jksinton** [comment]
@dwillis Yeah the presidential results are done. If you have any issues with it let me know.

**Comment by scottcame** [comment]
I have converted the Briscoe County file and will submit it in a PR later this weekend

**Comment by jksinton** [comment]
@dwillis I've started developing a python script to churn through all the election results for Harris County: https://github.com/jksinton/Convert-Election-Results

Right now it pretty much prints each page as csv.

**Comment by dwillis** [comment]
@jksinton that sounds great. let me know if you have questions.

**Comment by jksinton** [comment]
@dwillis Uploaded the ocr output for harris county to this branch here: https://github.com/jksinton/Convert-Election-Results/tree/harris-2016/csv

Each office has it's own file. The ocr output needs to be reviewed and corrected for inaccuracies. Also, I repeat the header for each page of output generated. I did this specifically to address the presidential results, which spans 30 pages with one set of columns and another 30 pages with a different set of columns. Those extra headers can be deleted.

**Comment by dwillis** [comment]
@jksinton thanks - i'll take a look at this.

**Comment by jksinton** [comment]
Moved the ocr data for Harris to a separate repository: https://github.com/jksinton/Harris-County-Election-Results
