### ISSUE TITLE
2020 General - Bexar County missing votes

### ISSUE THREAD

**Issue by rev2solutions** [openelections/openelections-data-tx#322]
It looks like some votes are missing from the Bexar Couty file. Sum of votes in file is 770,569 sum of votes on the offficial results site is 770,818. May be related to some write-in candidates not being included in 'write-in' total.

Official site: https://results.texas-election.com/contestdetails?officeID=1001&officeName=PRESIDENT%2FVICE-PRESIDENT&officeType=FEDERAL%20OFFICES&from=race

**Comment by dwillis** [comment]
Have consolidated this into #344
