### ISSUE TITLE
Incorrect Candidates for US House 23 in 20201103__tx__general__pecos__precinct

### ISSUE THREAD

**Issue by choprashweta** [openelections/openelections-data-tx#323]
The candidates mentioned in the general election results [file](https://github.com/openelections/openelections-data-tx/blob/master/2020/counties/20201103__tx__general__pecos__precinct.csv) for the US House 23 Race in Pecos County, TX are incorrect. The mentioned candidates are from TX-11. The correct Dem candidate should be Gina Ortiz Jones and Rep candidate should be Tony Gonzales.

Correct Candidates source: https://www.nytimes.com/interactive/2020/11/03/us/elections/results-texas-house-district-23.html

**Comment by dwillis** [comment]
@choprashweta thank you! fixed now.
