### ISSUE TITLE
Precinct-level data error: 2020 general election, Brazoria County

### ISSUE THREAD

**Issue by joe70s** [openelections/openelections-data-tx#349]
Precinct 11 should total to 1,614 votes for Trump/Pence, not 1,057 votes.  A data record for precinct 11-AISD-IC-5 is missing, which presumably contains the missing 557 votes:

https://www.brazoriacountyclerk.net/home/showpublisheddocument/6887/637425026123230000  

See page 68.

**Comment by dwillis** [comment]
@joe70s right you are - the data file produced by Brazoria is missing that line.
