### ISSUE TITLE
Inconsistent values in 2016 Wilson County general source file

### ISSUE THREAD

**Issue by warwickmm** [openelections/openelections-data-tx#378]
The [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2016/2016%20Wilson,%20TX%20precinct-level%20election%20results.pdf) for the 2016 Wilson County general results contains values that are inconsistent.  There are handwritten corrections to election day votes that do not have corresponding corrections to the total votes (`1818` should probably be `1819`, and `333` should probably be `334`):

![image](https://user-images.githubusercontent.com/17345532/133304223-01f58133-3306-4b1c-9fea-267b1f7df09f.png)

In these cases, do we want our files to reflect these inconsistencies, or should we amend the totals?

**Comment by dwillis** [comment]
@warwickmm our practice is to amend the totals.

**Comment by warwickmm** [comment]
Ok, I'll submit a pull request for this.
